### ISSUE TITLE
Build Docx To PDF Conversion

### ISSUE THREAD

**Issue by klondikemarlen** [burkkyy/topdf#1]
# Context

Add ability to convert a docx to a pdf via the node.js command line

e.g.
```bash
node topdf input.docx
```
expected output `input.pdf`

**Comment by burkkyy** [comment]
To convert file `example.docx` to pdf:
```bash
docker build . -t topdf
docker run -it --rm -v .:/root/env topdf libreoffice --headless --convert-to pdf ./example.docx
```

This is just to prove it can convert docx to pdf. Moving from this issue to creating easier functionality.
